name: Update Luna App Folder

on:
  push:
    paths:
      - 'app/dev/**'

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build dev
        run: |
          cd app/dev
          cargo build --release

      - name: update prod folder
        if: success()
        run: |
          rm -rf app/dev/target
          rm -rf app/prod
          # use rsync to only copy source, not build artifacts or dotfiles
          rsync -av --exclude 'target' --exclude '.git' --exclude '.gitignore' --exclude '.DS_Store' app/dev/ app/prod/

      - name: commit and push if changed
        if: success()
        run: |
          git config user.name "luna app"
          git config user.email "app@lu.na"
          git add -f app/prod
          git diff --cached --quiet && echo "no changes to commit" || (git commit -m "ci: update app/prod to last successful build" && git push)